// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voefaivndzxdyxwfswgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvZWZhaXZuZHp4ZHl4d2Zzd2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzM5NjEsImV4cCI6MjA2NzE0OTk2MX0.HLLLujMvWwfk0-lci_rg4FSxGR0_Z51Ftccc9eR546w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});